version: '{branch}-{build}'
build: off
configuration: Release
environment:
  matrix:
    - TESTENV: '3.7-nocover-64'
      INSTALL_LIBPYTHON: libpython
      PYTHON_VERSION: '3.7'
      MINICONDA_HOME: C:\Miniconda-x64
      TESTSCRIPT: 'pytest -vs --cov=sami2py/'
