language: python
dist: xenial
matrix:
  include:
    - python: 3.5
    - python: 3.6
    - python: 3.7

services: xvfb

addons:
  apt:
    packages:
    - gfortran

before_install:
  - pip install pytest-cov
  - pip install coveralls
  - pip install future
  - pip install matplotlib

install:
  - python setup.py install

before_script:
  # set up display screen
  - export DISPLAY=:99.0

script:
  - pytest -vs --cov=sami2py/

after_success:
  - coveralls
