language: python
dist: xenial
matrix:
  include:
    - python: 2.7
    - python: 3.5
    - python: 3.6
    - python: 3.7

addons:
  apt:
    packages:
    - gfortran

before_install:
  - pip install pytest
  - pip install pytest-cov
  - pip install coveralls
  - pip install future
  - pip install matplotlib

install:
  - python setup.py install

script:
  - pytest -v --cov=sami2py/

after_success:
  - coveralls
